"use client";
import { useMemo } from "react";
import { BarChart, Bar, CartesianGrid, PieChart, Pie, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Sidebar } from "@/components/Sidebar";
import { universities } from "@/lib/universities";

const colors = ["#ef4444", "#f59e0b", "#10b981"];
const num = (v:string) => { const m=v.replace(/,/g,"").match(/[0-9]+(?:\.[0-9]+)?/); return m ? Number(m[0]) : 0; };
export default function AnalyticsPage(){
 const countries=useMemo(()=>Array.from(new Set(universities.map(u=>u.country))).map(country=>{const us=universities.filter(u=>u.country===country);return {country,universities:us.length,tuition:Math.round(us.reduce((s,u)=>s+num(u.tuition),0)/Math.max(us.length,1)),living:Math.round(us.reduce((s,u)=>s+num(u.living),0)/Math.max(us.length,1))}}),[]);
 const classes=useMemo(()=>["Reach","Target","Safe"].map(name=>({name,value:universities.filter(u=>u.classification.includes(name)).length})),[]);
 const total=universities.map(u=>num(u.totalCost)).filter(Boolean); const salary=universities.map(u=>num(u.startingSalary)).filter(Boolean); const employ=universities.map(u=>num(u.employability)).filter(Boolean);
 return <div className="min-h-screen bg-slate-50"><Sidebar/><main className="ml-64 min-h-screen"><header className="border-b border-slate-200 bg-white px-8 py-6"><p className="text-sm font-medium text-blue-600">Admissions 2027</p><h1 className="mt-1 text-2xl font-semibold">Analytics</h1><p className="mt-1 text-sm text-slate-500">Decision-support statistics from the current university database.</p></header><div className="space-y-6 p-8">
 <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{[["Universities",universities.length],["Reach",classes[0].value],["Target",classes[1].value],["Safe",classes[2].value],["Avg employability",employ.length?(employ.reduce((a,b)=>a+b,0)/employ.length).toFixed(1):"—"]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{l}</p><p className="mt-2 text-2xl font-semibold">{v}</p></div>)}</section>
 <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="font-semibold">Reach / Target / Safe</h2><div className="mt-4 h-72"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={classes} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={95} label>{classes.map((e,i)=><Cell key={e.name} fill={colors[i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div></div><div className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="font-semibold">Tuition and living by country</h2><div className="mt-4 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={countries}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="country" tick={{fontSize:11}}/><YAxis/><Tooltip/><Bar dataKey="tuition" name="Tuition" fill="#2563eb"/><Bar dataKey="living" name="Living" fill="#94a3b8"/></BarChart></ResponsiveContainer></div></div></section>
 <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="font-semibold">Cost and outcome statistics</h2><div className="mt-5 grid gap-5 md:grid-cols-3"><Stat label="Average total cost" value={total.length?total.reduce((a,b)=>a+b,0)/total.length:0} note="Parsed from displayed cost figures; mixed currencies are not converted."/><Stat label="Average starting salary" value={salary.length?salary.reduce((a,b)=>a+b,0)/salary.length:0} note="Parsed from displayed salary figures; mixed currencies are not converted."/><Stat label="Average employability" value={employ.length?employ.reduce((a,b)=>a+b,0)/employ.length:0} note="Only records with numeric ratings are included."/></div></section>
 </div></main></div>
}
function Stat({label,value,note}:{label:string;value:number;note:string}){return <div className="rounded-xl bg-slate-50 p-4"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value?value.toFixed(1):"—"}</p><p className="mt-1 text-xs text-slate-400">{note}</p></div>}
