"use client";
import { useState } from "react";
import { FileSpreadsheet, FileText, UploadCloud, CheckCircle2 } from "lucide-react";
import * as XLSX from "xlsx";
import { Sidebar } from "@/components/Sidebar";
const KEY="universityhub-imported-records";
export default function ImportPage(){
 const [status,setStatus]=useState(""); const [rows,setRows]=useState<Record<string,unknown>[]>([]); const [name,setName]=useState("");
 async function load(file:File){setName(file.name);setStatus("");
  if(/\.xlsx?$/.test(file.name.toLowerCase())){const wb=XLSX.read(await file.arrayBuffer(),{type:"array"});const out:Record<string,unknown>[]=[];for(const s of wb.SheetNames){XLSX.utils.sheet_to_json<Record<string,unknown>>(wb.Sheets[s],{defval:""}).forEach(r=>out.push({...r,_sourceSheet:s}));}save(out,file.name);setRows(out.slice(0,10));setStatus(`Imported ${out.length} rows from ${wb.SheetNames.length} sheet(s).`);return;}
  if(/\.md(own)?$|\.markdown$/.test(file.name.toLowerCase())){const text=await file.text();const out=parse(text);save(out,file.name);setRows(out.slice(0,10));setStatus(`Imported ${out.length} university blocks. Raw source text is retained.`);return;}setStatus("Please upload .md, .markdown, .xlsx or .xls.");}
 function save(records:Record<string,unknown>[],source:string){const old=JSON.parse(localStorage.getItem(KEY)||"[]");localStorage.setItem(KEY,JSON.stringify([...old,{source,importedAt:new Date().toISOString(),records}]));}
 return <div className="min-h-screen bg-slate-50"><Sidebar/><main className="ml-64 min-h-screen"><header className="border-b border-slate-200 bg-white px-8 py-6"><p className="text-sm font-medium text-blue-600">Data management</p><h1 className="mt-1 text-2xl font-semibold">Import & merge</h1><p className="mt-1 text-sm text-slate-500">Import the complete report and your additional Excel data without discarding source fields.</p></header><div className="space-y-6 p-8"><div className="grid gap-5 md:grid-cols-2"><Card icon={<FileText/>} title="Markdown report" accept=".md,.markdown" onFile={load}/><Card icon={<FileSpreadsheet/>} title="Excel shortlist" accept=".xlsx,.xls" onFile={load}/></div>{status&&<div className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5 text-emerald-800"><div className="flex gap-3"><CheckCircle2 size={20}/><div><p className="font-medium">{status}</p><p className="text-sm opacity-75">{name}</p></div></div></div>}<section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="font-semibold">Raw import preview</h2><p className="text-sm text-slate-500">First 10 records. Values are not summarized.</p></div><div className="overflow-x-auto">{rows.length?<table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50">{<tr>{Object.keys(rows[0]).map(k=><th key={k} className="px-4 py-3 text-xs uppercase text-slate-500">{k}</th>)}</tr>}</thead><tbody className="divide-y">{rows.map((r,i)=><tr key={i}>{Object.keys(rows[0]).map(k=><td key={k} className="max-w-[320px] whitespace-pre-wrap px-4 py-3 align-top">{String(r[k]??"")}</td>)}</tr>)}</tbody></table>:<div className="p-12 text-center text-sm text-slate-400">Upload a source file to preview it.</div>}</div></section></div></main></div>;
}
function Card({icon,title,accept,onFile}:{icon:React.ReactNode;title:string;accept:string;onFile:(f:File)=>void}){return <label className="cursor-pointer rounded-2xl border border-slate-200 bg-white p-6 shadow-sm hover:border-blue-300"><input type="file" accept={accept} className="hidden" onChange={e=>e.target.files?.[0]&&onFile(e.target.files[0])}/><div className="flex justify-between text-blue-600"><span>{icon}</span><UploadCloud size={20}/></div><h2 className="mt-5 font-semibold">{title}</h2><p className="mt-2 text-sm text-slate-500">Choose a source file and preserve its raw fields for later mapping and deduplication.</p><span className="mt-4 inline-block text-sm font-medium text-blue-600">Choose file →</span></label>}
function parse(text:string){const lines=text.split(/\r?\n/),out:Record<string,unknown>[]=[];const countries=["United Kingdom","Canada","Singapore","Germany","India"];let country="",cur:Record<string,unknown>|null=null;for(const line of lines){const t=line.trim();if(countries.includes(t)){country=t;continue;}const h=t.match(/^\*\*(?:\d+\.\s*)?(.+?)\*\*$/);if(h){if(cur)out.push(cur);cur={university:h[1].trim(),country,raw:""};continue;}if(cur){cur.raw=String(cur.raw)+line+"\n";const m=t.match(/^\*{0,2}([^:]+):\*{0,2}\s*(.*)$/);if(m)cur[m[1].trim()]=m[2].trim();}}if(cur)out.push(cur);return out;}
