"use client";

import { useMemo, useState } from "react";
import { universities } from "@/lib/universities";
import { Sidebar } from "@/components/Sidebar";

type Application = { id: string; universityId: string; status: string; offer: string; scholarship: string; visa: string; accommodation: string; finalDecision: string; notes: string };
const KEY = "universityhub-applications";
const statuses = ["Shortlisted","Preparing","Submitted","Interview","Offer","Rejected","Withdrawn"];
const yesNo = ["Not started","In progress","Complete","Not applicable"];
function load(): Application[] { if (typeof window === "undefined") return []; try { return JSON.parse(localStorage.getItem(KEY) || "[]"); } catch { return []; } }
function save(items: Application[]) { localStorage.setItem(KEY, JSON.stringify(items)); }

export default function TrackerPage() {
  const [items, setItems] = useState<Application[]>(load);
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("All");
  const visible = useMemo(() => universities.filter(u => (!query || `${u.name} ${u.country} ${u.major}`.toLowerCase().includes(query.toLowerCase())) && (filter === "All" || (items.find(a=>a.universityId===u.id)?.status || "Shortlisted") === filter)), [query, filter, items]);
  const get = (id:string) => items.find(a=>a.universityId===id) || { id: id, universityId:id, status:"Shortlisted", offer:"Not started", scholarship:"Not started", visa:"Not started", accommodation:"Not started", finalDecision:"Not decided", notes:"" };
  const update = (id:string, patch:Partial<Application>) => { const next = items.some(a=>a.universityId===id) ? items.map(a=>a.universityId===id?{...a,...patch}:a) : [...items,{...get(id),...patch}]; setItems(next); save(next); };
  return <div className="min-h-screen bg-slate-50"><Sidebar/><main className="ml-64 min-h-screen"><header className="border-b border-slate-200 bg-white px-8 py-6"><p className="text-sm font-medium text-blue-600">Admissions 2027</p><h1 className="mt-1 text-2xl font-semibold">Application Tracker</h1><p className="mt-1 text-sm text-slate-500">Track every application milestone. Changes persist in your browser.</p></header><div className="space-y-5 p-8">
  <div className="grid gap-4 md:grid-cols-4">{statuses.slice(0,4).map(s=><div key={s} className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-500">{s}</p><p className="mt-2 text-2xl font-semibold">{items.filter(a=>a.status===s).length}</p></div>)}</div>
  <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-[1fr_180px]"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search applications..." className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm outline-none"/><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm"><option>All</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div></section>
  <section className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[1250px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">University</th><th className="px-3 py-3">Deadline</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Offer</th><th className="px-3 py-3">Scholarship</th><th className="px-3 py-3">Visa</th><th className="px-3 py-3">Accommodation</th><th className="px-3 py-3">Decision</th><th className="px-3 py-3">Notes</th></tr></thead><tbody className="divide-y divide-slate-100">{visible.map(u=>{const a=get(u.id);return <tr key={u.id}><td className="px-5 py-4"><div className="font-semibold">{u.name}</div><div className="text-xs text-slate-400">{u.country} · {u.major}</div></td><td className="px-3 py-4 whitespace-nowrap text-slate-600">{u.deadline || "—"}</td><td className="px-3 py-4"><select value={a.status} onChange={e=>update(u.id,{status:e.target.value})} className="rounded-lg border border-slate-200 px-2 py-1.5 text-xs">{statuses.map(s=><option key={s}>{s}</option>)}</select></td><td className="px-3 py-4"><select value={a.offer} onChange={e=>update(u.id,{offer:e.target.value})} className="rounded-lg border border-slate-200 px-2 py-1.5 text-xs">{yesNo.map(s=><option key={s}>{s}</option>)}</select></td><td className="px-3 py-4"><select value={a.scholarship} onChange={e=>update(u.id,{scholarship:e.target.value})} className="rounded-lg border border-slate-200 px-2 py-1.5 text-xs">{yesNo.map(s=><option key={s}>{s}</option>)}</select></td><td className="px-3 py-4"><select value={a.visa} onChange={e=>update(u.id,{visa:e.target.value})} className="rounded-lg border border-slate-200 px-2 py-1.5 text-xs">{yesNo.map(s=><option key={s}>{s}</option>)}</select></td><td className="px-3 py-4"><select value={a.accommodation} onChange={e=>update(u.id,{accommodation:e.target.value})} className="rounded-lg border border-slate-200 px-2 py-1.5 text-xs">{yesNo.map(s=><option key={s}>{s}</option>)}</select></td><td className="px-3 py-4"><input value={a.finalDecision} onChange={e=>update(u.id,{finalDecision:e.target.value})} className="w-32 rounded-lg border border-slate-200 px-2 py-1.5 text-xs" placeholder="Decision"/></td><td className="px-3 py-4"><input value={a.notes} onChange={e=>update(u.id,{notes:e.target.value})} className="w-48 rounded-lg border border-slate-200 px-2 py-1.5 text-xs" placeholder="Add note..."/></td></tr>})}</tbody></table></section>
 </div></main></div>;
}
