"use client";
import { useRef, useState } from "react";
import { Download, Upload, Database, ShieldCheck } from "lucide-react";
import { Sidebar } from "@/components/Sidebar";

const keys = ["universityhub-university-edits","universityhub-applications","universityhub-imported-records"];
export default function DataCenter(){
 const inputRef=useRef<HTMLInputElement>(null); const [message,setMessage]=useState("");
 const exportData=()=>{const payload=Object.fromEntries(keys.map(k=>[k,localStorage.getItem(k)])); const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),data:payload},null,2)],{type:"application/json"}); const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url; a.download="universityhub-backup.json"; a.click(); URL.revokeObjectURL(url); setMessage("Backup exported successfully.");};
 const importData=(file:File)=>{const reader=new FileReader(); reader.onload=()=>{try{const parsed=JSON.parse(String(reader.result)); for(const k of keys) if(typeof parsed.data?.[k]==="string") localStorage.setItem(k,parsed.data[k]); setMessage("Backup restored. Refresh the relevant pages to see the restored data.");}catch{setMessage("That backup file could not be read.");}}; reader.readAsText(file);};
 return <div className="min-h-screen bg-slate-50"><Sidebar/><main className="ml-64 min-h-screen"><header className="border-b bg-white px-8 py-6"><p className="text-sm font-medium text-blue-600">UniversityHub</p><h1 className="mt-1 text-2xl font-semibold">Data Center</h1><p className="mt-1 text-sm text-slate-500">Back up your editable records and imported data before making major changes.</p></header><div className="max-w-4xl space-y-6 p-8"><section className="grid gap-6 md:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><Database className="text-blue-600" size={22}/><h2 className="mt-4 font-semibold">Local database backup</h2><p className="mt-2 text-sm leading-6 text-slate-500">Exports application progress, university edits, and imported/merged records stored by UniversityHub in this browser.</p><button onClick={exportData} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-medium text-white"><Download size={16}/> Export backup</button></div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><ShieldCheck className="text-emerald-600" size={22}/><h2 className="mt-4 font-semibold">Restore backup</h2><p className="mt-2 text-sm leading-6 text-slate-500">Restore a previously exported UniversityHub JSON backup. Existing local records for the included data sets will be replaced.</p><input ref={inputRef} type="file" accept="application/json,.json" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)importData(f)}}/><button onClick={()=>inputRef.current?.click()} className="mt-5 inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-medium"><Upload size={16}/> Restore backup</button></div></section>{message&&<div className="rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm text-blue-800">{message}</div>}<section className="rounded-2xl border border-amber-100 bg-amber-50 p-6"><h2 className="font-semibold">Important</h2><p className="mt-2 text-sm leading-6 text-slate-700">The canonical university research dataset remains in the repository. This backup covers browser-editable state and imported data, so your application tracking and manual edits can be moved between browsers without changing the source dataset.</p></section></div></main></div>;
}
