"use client";
import { useMemo } from "react";
import { Sidebar } from "@/components/Sidebar";
import { universities } from "@/lib/universities";
import { VERIFIED_REQUIREMENTS } from "@/lib/verifiedRequirements";

const fields=["name","country","degree","major","ib","hl","english","entranceTest","acceptance","tuition","living","totalCost","classification","deadline","qs","the","scholarship","academics","research","internship","employability","startingSalary","recruiters","workRights","recommendation","rationale","notes"] as const;
export default function DataIntegrityPage(){
 const duplicateIds=useMemo(()=>{const seen=new Set<string>(), dup=new Set<string>();for(const u of universities){if(seen.has(u.id))dup.add(u.id);seen.add(u.id)}return [...dup]},[]);
 const rows=useMemo(()=>universities.map(u=>{const missing=fields.filter(f=>!String(u[f]??"").trim());const verified=VERIFIED_REQUIREMENTS.some(v=>v.university.toLowerCase()===u.name.toLowerCase());return {...u,missing,verified}}),[]);
 const missingCount=rows.reduce((n,r)=>n+r.missing.length,0), complete=rows.filter(r=>r.missing.length===0).length;
 return <div className="min-h-screen bg-slate-50"><Sidebar/><main className="ml-64 min-h-screen"><header className="border-b border-slate-200 bg-white px-8 py-6"><p className="text-sm font-medium text-blue-600">Database quality control</p><h1 className="mt-1 text-2xl font-semibold">Data Integrity</h1><p className="mt-1 text-sm text-slate-500">A live audit of the canonical university records. Blank source fields are surfaced rather than filled with guesses.</p></header><div className="space-y-6 p-8"><div className="grid gap-4 md:grid-cols-4">{[["Universities",universities.length], ["Complete core records",complete], ["Missing core fields",missingCount], ["Duplicate IDs",duplicateIds.length]].map(([label,value])=><div key={label as string} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-medium uppercase tracking-wide text-slate-400">{label as string}</p><p className="mt-2 text-3xl font-semibold">{value as number}</p></div>)}</div>{duplicateIds.length>0&&<div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-800">Duplicate IDs detected: {duplicateIds.join(", ")}</div>}<section className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">University</th><th className="px-3 py-3">Country</th><th className="px-3 py-3">Core completeness</th><th className="px-3 py-3">Official verification</th><th className="px-3 py-3">Missing fields</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(r=><tr key={r.id}><td className="px-5 py-4 font-semibold">{r.name}</td><td className="px-3 py-4">{r.country}</td><td className="px-3 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${r.missing.length===0?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{r.missing.length===0?"Complete":`${fields.length-r.missing.length}/${fields.length}`}</span></td><td className="px-3 py-4">{r.verified?<span className="text-emerald-700">Verified registry</span>:<span className="text-slate-400">Not yet verified</span>}</td><td className="max-w-xl px-3 py-4 text-xs text-slate-500">{r.missing.length?r.missing.join(", "):"None"}</td></tr>)}</tbody></table></section></div></main></div>}
