"use client";
import { useMemo } from "react";
import { Sidebar } from "@/components/Sidebar";
import { universities } from "@/lib/universities";
import { VERIFIED_REQUIREMENTS } from "@/lib/verifiedRequirements";

const fields=["degree","major","ib","hl","english","entranceTest","acceptance","tuition","living","totalCost","classification","status","deadline","qs","the","scholarship","academics","research","internship","employability","startingSalary","recruiters","workRights","recommendation","rationale","notes","officialIB","officialSource","officialTestSource","raw"] as const;
const labels:Record<string,string>={degree:"Degree",major:"Recommended Major",ib:"Exact IB Requirement",hl:"HL Subject Requirements",english:"English Language Requirement",entranceTest:"Entrance Test Requirement",acceptance:"Acceptance Rate",tuition:"Tuition",living:"Living Cost",totalCost:"Total Cost",classification:"Reach / Target / Safer",status:"Application Status",deadline:"Deadline",qs:"QS Ranking",the:"THE Ranking",scholarship:"Scholarships",academics:"Academic Highlights",research:"Research Strength",internship:"Internship / Co-op",employability:"Employability Rating",startingSalary:"Starting Salary",recruiters:"Recruiters",workRights:"Post-study Work Rights",recommendation:"Recommendation",rationale:"Rationale",notes:"Notes",officialIB:"Officially Verified IB Requirement",officialSource:"Official Admissions Source",officialTestSource:"Official Test / Requirements Source",raw:"Original Source Record"};
export default function DataIntegrityPage(){
 const duplicateIds=useMemo(()=>{const seen=new Set<string>(),dup=new Set<string>();for(const u of universities){if(seen.has(u.id))dup.add(u.id);seen.add(u.id)}return [...dup]},[]);
 const rows=useMemo(()=>universities.map(u=>{const missing=fields.filter(f=>!String(u[f]??"").trim());const verified=VERIFIED_REQUIREMENTS.some(v=>v.university.toLowerCase()===u.name.toLowerCase());return {...u,missing,verified}}),[]);
 const missingCount=rows.reduce((n,r)=>n+r.missing.length,0),complete=rows.filter(r=>r.missing.length===0).length,verifiedCount=rows.filter(r=>r.verified).length;
 return <div className="min-h-screen bg-slate-50"><Sidebar/><main className="ml-64 min-h-screen"><header className="border-b border-slate-200 bg-white px-8 py-6"><p className="text-sm font-medium text-blue-600">Database quality control</p><h1 className="mt-1 text-2xl font-semibold">Data Integrity</h1><p className="mt-1 text-sm text-slate-500">Live audit of every canonical university record. Blank source fields remain visible instead of being guessed.</p></header><div className="space-y-6 p-8"><div className="grid gap-4 md:grid-cols-4"><Metric label="Universities" value={universities.length}/><Metric label="Complete records" value={complete}/><Metric label="Missing fields" value={missingCount}/><Metric label="Officially verified" value={verifiedCount}/></div>{duplicateIds.length>0&&<div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-800">Duplicate IDs detected: {duplicateIds.join(", ")}</div>}<section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Field-level audit</h2><p className="mt-1 text-sm text-slate-500">Audits all {fields.length} tracked database fields, including original-source and official-verification fields.</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-medium text-blue-700">{fields.length} fields</span></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1200px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">University</th><th className="px-3 py-3">Country</th><th className="px-3 py-3">Completeness</th><th className="px-3 py-3">Official verification</th><th className="px-3 py-3">Missing fields</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(r=><tr key={r.id}><td className="px-5 py-4 font-semibold">{r.name}</td><td className="px-3 py-4">{r.country}</td><td className="px-3 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${r.missing.length===0?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{fields.length-r.missing.length}/{fields.length}</span></td><td className="px-3 py-4">{r.verified?<span className="text-emerald-700">Verified registry</span>:<span className="text-slate-400">Not yet verified</span>}</td><td className="max-w-2xl px-3 py-4 text-xs text-slate-500">{r.missing.length?r.missing.map(f=>labels[f]).join(", "):"None"}</td></tr>)}</tbody></table></div></section></div></main></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-medium uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>}
