export type VerifiedRequirement={university:string;ibRequirement?:string;hlRequirements?:string;english?:string;entrance?:string;deadline?:string;tuition?:string;internship?:string;scholarships?:string;source:string;status:string};
export const VERIFIED_REQUIREMENTS:VerifiedRequirement[]=[
{university:"Imperial College London",ibRequirement:"40 IB points for MEng Mechanical Engineering (2027 entry).",entrance:"ESAT required for Mechanical Engineering.",source:"https://www.imperial.ac.uk/study/courses/undergraduate/mechanical-engineering/",status:"Official 2027 verification"},
{university:"University College London (UCL)",ibRequirement:"Physics BSc 2027: 39 IB points, including 19 HL points with 7 and 6 in Mathematics and Physics; no HL below 5.",deadline:"13 January 2027",source:"https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/physics-bsc",status:"Official 2027 verification"},
{university:"University of Manchester",ibRequirement:"Mechanical Engineering 2027: 38 IB points with 7,7,6 at HL, including Mathematics and Physics.",hlRequirements:"Mathematics AA or AI accepted.",source:"https://www.manchester.ac.uk/study/undergraduate/courses/2027/03389/beng-mechanical-engineering/",status:"Official 2027 verification"},
{university:"University of Bath",ibRequirement:"Mechanical Engineering BEng 2027: 36 IB points with 6,6,6 or 7,6,5 at HL, including 6 in Physics and 6 in HL Mathematics.",deadline:"13 January 2027 for overseas applicants",source:"https://www.bath.ac.uk/courses/undergraduate-2027/mechanical-engineering/beng-mechanical-engineering/",status:"Official 2027 verification"},
{university:"University of Toronto",ibRequirement:"IB Diploma and at least 30 predicted points excluding TOK/EE bonus points under official Engineering guidance; competitive scores are higher.",hlRequirements:"Engineering prerequisites include Mathematics, Chemistry, Physics and English.",entrance:"Engineering Online Student Profile required.",source:"https://discover.engineering.utoronto.ca/how-to-apply/outofcanada/",status:"Official policy verification"},
{university:"University of British Columbia",ibRequirement:"IB Diploma applicants require at least three HL courses; no single guaranteed IB cutoff is published for Engineering.",hlRequirements:"Applied Science requires Mathematics AA SL/HL or AI HL, Chemistry and Physics.",entrance:"Personal Profile required.",source:"https://you.ubc.ca/ubc_programs/engineering-physics/",status:"Official programme verification"},
{university:"University of Waterloo",ibRequirement:"Engineering IB applicants require six IB courses, minimum 4 in each, and minimum total 32 excluding Diploma points; no absolute cutoff.",entrance:"AIF and supplementary Engineering requirements apply.",source:"https://uwaterloo.ca/engineering/future-students/applying/admission-requirements",status:"Official policy verification"},
{university:"Queen's University",ibRequirement:"General IB policy: six passed subjects, at least three HL, minimum 28 excluding bonus points; programmes may require higher results.",source:"https://www.queensu.ca/academic-calendar/arts-science/admission-regulations/",status:"Official general-policy verification"},
{university:"National University of Singapore",hlRequirements:"Mechanical Engineering requires Higher Level Mathematics; programme prerequisites apply.",source:"https://cde.nus.edu.sg/me/undergraduate/admissions/",status:"Official programme verification"},
{university:"Nanyang Technological University",hlRequirements:"Mechanical Engineering requires HL Mathematics plus an accepted HL science subject such as Physics, Chemistry, Biology or Computer Science.",source:"https://www.ntu.edu.sg/admissions/undergraduate/admission-guide/international-qualifications/ib-diploma",status:"Official policy verification"},
{university:"Technical University of Munich (TUM)",entrance:"Mechanical Engineering uses an aptitude-assessment procedure.",english:"German proficiency required for the German-taught programme.",deadline:"Current published winter-semester period: 15 May–15 July; verify 2027 dates when released.",tuition:"€3,000 per semester for international students from third countries, plus semester fee.",internship:"At least eight weeks of manufacturing internship required.",source:"https://www.tum.de/en/studies/degree-programs/detail/mechanical-engineering-bachelor-of-science-bsc",status:"Official current verification; 2027 confirmation pending"},
{university:"Karlsruhe Institute of Technology (KIT)",ibRequirement:"KIT accepts the International Baccalaureate as a university entrance qualification; no single fixed IB total cutoff published on the cited programme page.",english:"B2 English minimum; IELTS 6.5 or TOEFL iBT 90 or accepted equivalent; IB English grade 5+ can satisfy stated waiver conditions.",deadline:"April 30 for the cited cycle; 2027/28 portal expected to reopen in December 2026.",source:"https://www.sle.kit.edu/english/vorstudium/bachelor-mechanical-engineering-international.php",status:"Official programme verification"},
{university:"Ashoka University",ibRequirement:"IB Diploma, IB Course and Career-related Programme students are eligible; holistic admissions with no single published IB cutoff.",entrance:"Mandatory On-the-Spot Essay and Ashoka Aptitude Assessment.",scholarships:"Need-based and merit scholarships available.",source:"https://www.ashoka.edu.in/undergraduate-programme-holistic-admissions-and-process/",status:"Official policy verification"},
{university:"FLAME University",ibRequirement:"IB Diploma is the minimum eligibility requirement for IB students.",entrance:"FEAT forms part of admissions; SAT/ACT can be submitted under the stated policy.",scholarships:"Scholarship opportunities available; exact 2027 awards require current schedule.",source:"https://2025.flame.edu.in/admissions/ug/minimum-eligibility",status:"Official eligibility verification"}
];
export function getVerifiedRequirement(name:string){const n=name.toLowerCase().replace(/[^a-z0-9]/g,"");return VERIFIED_REQUIREMENTS.find(v=>v.university.toLowerCase().replace(/[^a-z0-9]/g,"")===n)}
