"use client";
import { useMemo, useState } from "react";
import { Sidebar } from "@/components/Sidebar";
import { universities } from "@/lib/universities";

type DocState = Record<string, Record<string, boolean>>;
const KEY="universityhub-documents";
const docs=["Passport","IB predicted grades / transcript","Final IB transcript","Personal statement / essay","Teacher recommendation","CV / activities list","English test score","Entrance test score","Portfolio / supplementary material","Financial documents","Application fee confirmation","Scholarship application"];
function load():DocState{if(typeof window==="undefined")return {};try{return JSON.parse(localStorage.getItem(KEY)||"{}")}catch{return {}}}
export default function DocumentsPage(){const [state,setState]=useState<DocState>(load);const [q,setQ]=useState("");const visible=useMemo(()=>universities.filter(u=>`${u.name} ${u.country}`.toLowerCase().includes(q.toLowerCase())),[q]);const toggle=(uid:string,d:string)=>{const next={...state,[uid]:{...(state[uid]||{}),[d]:!(state[uid]?.[d])}};setState(next);localStorage.setItem(KEY,JSON.stringify(next))};const complete=(uid:string)=>docs.filter(d=>state[uid]?.[d]).length;return <div className="min-h-screen bg-slate-50"><Sidebar/><main className="ml-64 min-h-screen"><header className="border-b bg-white px-8 py-6"><p className="text-sm font-medium text-blue-600">Application preparation</p><h1 className="mt-1 text-2xl font-semibold">Documents & Checklist</h1><p className="mt-1 text-sm text-slate-500">Keep a separate document checklist for every university. Changes persist in your browser.</p></header><div className="space-y-5 p-8"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search universities..." className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none"/>{visible.map(u=>{const done=complete(u.id);return <section key={u.id} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between gap-4"><div><h2 className="font-semibold">{u.name}</h2><p className="mt-1 text-xs text-slate-500">{u.country} · {u.major}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-medium">{done}/{docs.length} complete</span></div><div className="mt-5 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{docs.map(d=><label key={d} className="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-100 p-3 text-sm hover:bg-slate-50"><input type="checkbox" checked={!!state[u.id]?.[d]} onChange={()=>toggle(u.id,d)}/><span className={state[u.id]?.[d]?"text-slate-400 line-through":"text-slate-700"}>{d}</span></label>)}</div></section>})}</div></main></div>}
