"use client";
import Link from "next/link";
import { Sidebar } from "@/components/Sidebar";

const verified = [
  { university: "Imperial College London", country: "United Kingdom", requirement: "40 IB points for MEng Mechanical Engineering (2027 entry). ESAT is required; Mechanical Engineering requires Mathematics 1, Mathematics 2 and Physics modules.", source: "https://www.imperial.ac.uk/study/courses/undergraduate/mechanical-engineering/", status: "Verified" },
  { university: "University College London (UCL)", country: "United Kingdom", requirement: "Physics BSc 2027: 39 IB points, including 19 points across three HL subjects with grades 7 and 6 in Mathematics and Physics, no HL below 5. Application deadline: 13 January 2027.", source: "https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/physics-bsc", status: "Verified" },
  { university: "University of Warwick", country: "United Kingdom", requirement: "Mechanical Engineering BEng 2027 course page verified; the official course page is the source of truth for the current 2027 entry requirement and application details.", source: "https://warwick.ac.uk/study/undergraduate/courses/beng-mechanical-engineering/", status: "Verified" },
  { university: "University of Manchester", country: "United Kingdom", requirement: "Mechanical Engineering 2027: 38 IB points overall with 7,7,6 at HL, including Mathematics and Physics. Mathematics AA or AI accepted.", source: "https://www.manchester.ac.uk/study/undergraduate/courses/2027/03389/beng-mechanical-engineering/", status: "Verified" },
  { university: "University of Bath", country: "United Kingdom", requirement: "Mechanical Engineering BEng 2027: 36 IB points with 6,6,6 or 7,6,5 at HL, including 6 in Physics and 6 in HL Mathematics. Mathematics must be HL. Overseas application deadline: 13 January 2027.", source: "https://www.bath.ac.uk/courses/undergraduate-2027/mechanical-engineering/beng-mechanical-engineering/", status: "Verified" },
];

export default function ResearchPage() {
  return <div className="min-h-screen bg-slate-50"><Sidebar/><main className="ml-64 min-h-screen"><header className="border-b border-slate-200 bg-white px-8 py-6"><p className="text-sm font-medium text-blue-600">Data quality</p><h1 className="mt-1 text-2xl font-semibold">Requirements Research</h1><p className="mt-1 max-w-3xl text-sm text-slate-500">Official-source verification is kept separate from the original report data so researched values never silently overwrite source material.</p></header><div className="space-y-5 p-8">{verified.map(v=><article key={v.university} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><h2 className="font-semibold text-slate-900">{v.university}</h2><p className="mt-1 text-xs text-slate-500">{v.country}</p><p className="mt-4 max-w-4xl text-sm leading-6 text-slate-700">{v.requirement}</p></div><span className="h-fit rounded-full border border-emerald-100 bg-emerald-50 px-3 py-1 text-xs font-medium text-emerald-700">{v.status}</span></div><div className="mt-5"><a href={v.source} target="_blank" rel="noreferrer" className="text-sm font-medium text-blue-700 hover:underline">Open official source</a></div></article>)}</div></main></div>;
}
